# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: h:/lab4/lab4-vivado/lab1.srcs/sources_1/bd/design_1/ip/design_1_calc_0_0_1/design_1_calc_0_0.xci
# IP: The module: 'design_1_calc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/lab4/lab4-vivado/lab1.srcs/sources_1/bd/design_1/ip/design_1_calc_0_0_1/constraints/calc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_calc_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: h:/lab4/lab4-vivado/lab1.srcs/sources_1/bd/design_1/ip/design_1_calc_0_0_1/design_1_calc_0_0.xci
# IP: The module: 'design_1_calc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/lab4/lab4-vivado/lab1.srcs/sources_1/bd/design_1/ip/design_1_calc_0_0_1/constraints/calc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_calc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
